import type { Deal } from "@/lib/firebase/deals";
import type { Laptop } from "@/lib/firebase/laptops";

export const SAMPLE_LAPTOPS: Laptop[] = [
  {
    id: "sample-1",
    name: "IdeaPad Slim 5",
    brand: "Lenovo",
    slug: "lenovo-ideapad-slim-5",
    price: 58990,
    specs: {
      ram: "16GB",
      storage: "512GB SSD",
      processor: "AMD Ryzen 5 7530U",
      gpu: "Integrated Radeon",
      display: '15.6" FHD IPS',
      battery: "Up to 8 hours",
      weight: "1.65 kg",
    },
    image: "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=600&q=80",
    affiliateUrl: "https://www.amazon.in",
    rating: 4.4,
    tags: ["Best Value", "Coding", "Lightweight"],
    isRecommended: true,
    branches: ["computer-science", "data-science", "electrical"],
    budgetRange: "50000-70000",
    updatedAt: new Date(),
  },
  {
    id: "sample-2",
    name: "MacBook Air M2",
    brand: "Apple",
    slug: "apple-macbook-air-m2",
    price: 99900,
    specs: {
      ram: "8GB",
      storage: "256GB SSD",
      processor: "Apple M2",
      gpu: "8-core GPU",
      display: '13.6" Liquid Retina',
      battery: "Up to 18 hours",
      weight: "1.24 kg",
    },
    image: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=600&q=80",
    affiliateUrl: "https://www.amazon.in",
    rating: 4.8,
    tags: ["Premium", "Battery King", "CS Favourite"],
    isRecommended: true,
    branches: ["computer-science", "ai", "data-science"],
    budgetRange: "100000-plus",
    updatedAt: new Date(),
  },
  {
    id: "sample-3",
    name: "HP Victus 15",
    brand: "HP",
    slug: "hp-victus-15",
    price: 67990,
    specs: {
      ram: "16GB",
      storage: "512GB SSD",
      processor: "Intel Core i5-13420H",
      gpu: "NVIDIA RTX 3050",
      display: '15.6" FHD 144Hz',
      battery: "Up to 6 hours",
      weight: "2.29 kg",
    },
    image: "https://images.unsplash.com/photo-1603302576837-37561b547382?w=600&q=80",
    affiliateUrl: "https://www.amazon.in",
    rating: 4.3,
    tags: ["Gaming", "CAD", "Mechanical"],
    isRecommended: false,
    branches: ["mechanical", "ai", "electronics"],
    budgetRange: "50000-70000",
    updatedAt: new Date(),
  },
  {
    id: "sample-4",
    name: "ASUS Vivobook 16",
    brand: "ASUS",
    slug: "asus-vivobook-16",
    price: 54990,
    specs: {
      ram: "16GB",
      storage: "512GB SSD",
      processor: "Intel Core i5-1335U",
      gpu: "Integrated Iris Xe",
      display: '16" FHD',
      battery: "Up to 7 hours",
      weight: "1.88 kg",
    },
    image: "https://images.unsplash.com/photo-1588872917328-466556784846?w=600&q=80",
    affiliateUrl: "https://www.amazon.in",
    rating: 4.2,
    tags: ["Large Screen", "Budget Friendly"],
    isRecommended: false,
    branches: ["civil", "electrical", "computer-science"],
    budgetRange: "50000-70000",
    updatedAt: new Date(),
  },
  {
    id: "sample-5",
    name: "Lenovo LOQ 15",
    brand: "Lenovo",
    slug: "lenovo-loq-15",
    price: 74990,
    specs: {
      ram: "16GB",
      storage: "512GB SSD",
      processor: "AMD Ryzen 7 7840HS",
      gpu: "NVIDIA RTX 4050",
      display: '15.6" FHD 144Hz',
      battery: "Up to 5 hours",
      weight: "2.38 kg",
    },
    image: "https://images.unsplash.com/photo-1525547719578-a2d4ac8915e2?w=600&q=80",
    affiliateUrl: "https://www.amazon.in",
    rating: 4.5,
    tags: ["AI/ML", "Gaming", "GPU"],
    isRecommended: true,
    branches: ["ai", "mechanical", "computer-science"],
    budgetRange: "70000-100000",
    updatedAt: new Date(),
  },
  {
    id: "sample-6",
    name: "Acer Aspire 5",
    brand: "Acer",
    slug: "acer-aspire-5",
    price: 44990,
    specs: {
      ram: "16GB",
      storage: "512GB SSD",
      processor: "AMD Ryzen 5 5500U",
      gpu: "Integrated Radeon",
      display: '15.6" FHD',
      battery: "Up to 7 hours",
      weight: "1.76 kg",
    },
    image: "https://images.unsplash.com/photo-1593642632823-8f785ba67e45?w=600&q=80",
    affiliateUrl: "https://www.amazon.in",
    rating: 4.1,
    tags: ["Budget Pick", "MATLAB"],
    isRecommended: false,
    branches: ["electrical", "electronics", "civil"],
    budgetRange: "under-50000",
    updatedAt: new Date(),
  },
];

export const SAMPLE_DEALS: Deal[] = [
  {
    id: "deal-1",
    laptopId: "sample-1",
    laptopName: "Lenovo IdeaPad Slim 5",
    originalPrice: 64990,
    dealPrice: 58990,
    discount: 9,
    platform: "Amazon.in",
    affiliateUrl: "https://www.amazon.in",
    validUntil: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
    isActive: true,
  },
  {
    id: "deal-2",
    laptopId: "sample-2",
    laptopName: "MacBook Air M2",
    originalPrice: 114900,
    dealPrice: 99900,
    discount: 13,
    platform: "Amazon.in",
    affiliateUrl: "https://www.amazon.in",
    validUntil: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000),
    isActive: true,
  },
  {
    id: "deal-3",
    laptopId: "sample-5",
    laptopName: "Lenovo LOQ 15",
    originalPrice: 82990,
    dealPrice: 74990,
    discount: 10,
    platform: "Flipkart",
    affiliateUrl: "https://www.flipkart.com",
    validUntil: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000),
    isActive: true,
  },
];
