import type { Deal } from "@/lib/firebase/deals";
import type { Laptop } from "@/lib/firebase/laptops";
import { LAPTOP_IMAGE_CATALOG } from "@/lib/laptopImages";

const img = (slug: string) => LAPTOP_IMAGE_CATALOG[slug] ?? "";

export const SAMPLE_LAPTOPS: Laptop[] = [
  {
    id: "sample-1",
    name: "IdeaPad Slim 5",
    brand: "Lenovo",
    slug: "lenovo-ideapad-slim-5",
    price: 58990,
    specs: {
      ram: "16GB",
      storage: "512GB SSD",
      processor: "AMD Ryzen 5 7530U",
      gpu: "Integrated Radeon",
      display: '15.6" FHD IPS',
      battery: "Up to 8 hours",
      weight: "1.65 kg",
    },
    image: img("lenovo-ideapad-slim-5"),
    affiliateUrl: "https://www.amazon.in",
    rating: 4.4,
    tags: ["Best Value", "Coding", "Lightweight"],
    isRecommended: true,
    branches: ["computer-science", "data-science", "electrical"],
    budgetRange: "50000-70000",
    updatedAt: new Date(),
  },
  {
    id: "sample-2",
    name: "MacBook Air M2",
    brand: "Apple",
    slug: "apple-macbook-air-m2",
    price: 99900,
    specs: {
      ram: "8GB",
      storage: "256GB SSD",
      processor: "Apple M2",
      gpu: "8-core GPU",
      display: '13.6" Liquid Retina',
      battery: "Up to 18 hours",
      weight: "1.24 kg",
    },
    image: img("apple-macbook-air-m2"),
    affiliateUrl: "https://www.amazon.in",
    rating: 4.8,
    tags: ["Premium", "Battery King", "CS Favourite"],
    isRecommended: true,
    branches: ["computer-science", "ai", "data-science"],
    budgetRange: "100000-plus",
    updatedAt: new Date(),
  },
  {
    id: "sample-3",
    name: "HP Victus 15",
    brand: "HP",
    slug: "hp-victus-15",
    price: 67990,
    specs: {
      ram: "16GB",
      storage: "512GB SSD",
      processor: "Intel Core i5-13420H",
      gpu: "NVIDIA RTX 3050",
      display: '15.6" FHD 144Hz',
      battery: "Up to 6 hours",
      weight: "2.29 kg",
    },
    image: img("hp-victus-15"),
    affiliateUrl: "https://www.amazon.in",
    rating: 4.3,
    tags: ["Gaming", "CAD", "Mechanical"],
    isRecommended: false,
    branches: ["mechanical", "ai", "electronics"],
    budgetRange: "50000-70000",
    updatedAt: new Date(),
  },
  {
    id: "sample-4",
    name: "ASUS Vivobook 16",
    brand: "ASUS",
    slug: "asus-vivobook-16",
    price: 54990,
    specs: {
      ram: "16GB",
      storage: "512GB SSD",
      processor: "Intel Core i5-1335U",
      gpu: "Integrated Iris Xe",
      display: '16" FHD',
      battery: "Up to 7 hours",
      weight: "1.88 kg",
    },
    image: img("asus-vivobook-16"),
    affiliateUrl: "https://www.amazon.in",
    rating: 4.2,
    tags: ["Large Screen", "Budget Friendly"],
    isRecommended: false,
    branches: ["civil", "electrical", "computer-science"],
    budgetRange: "50000-70000",
    updatedAt: new Date(),
  },
  {
    id: "sample-5",
    name: "Lenovo LOQ 15",
    brand: "Lenovo",
    slug: "lenovo-loq-15",
    price: 74990,
    specs: {
      ram: "16GB",
      storage: "512GB SSD",
      processor: "AMD Ryzen 7 7840HS",
      gpu: "NVIDIA RTX 4050",
      display: '15.6" FHD 144Hz',
      battery: "Up to 5 hours",
      weight: "2.38 kg",
    },
    image: img("lenovo-loq-15"),
    affiliateUrl: "https://www.amazon.in",
    rating: 4.5,
    tags: ["AI/ML", "Gaming", "GPU"],
    isRecommended: true,
    branches: ["ai", "mechanical", "computer-science"],
    budgetRange: "70000-100000",
    updatedAt: new Date(),
  },
  {
    id: "sample-6",
    name: "Acer Aspire 5",
    brand: "Acer",
    slug: "acer-aspire-5",
    price: 44990,
    specs: {
      ram: "16GB",
      storage: "512GB SSD",
      processor: "AMD Ryzen 5 5500U",
      gpu: "Integrated Radeon",
      display: '15.6" FHD',
      battery: "Up to 7 hours",
      weight: "1.76 kg",
    },
    image: img("acer-aspire-5"),
    affiliateUrl: "https://www.amazon.in",
    rating: 4.1,
    tags: ["Budget Pick", "MATLAB"],
    isRecommended: false,
    branches: ["electrical", "electronics", "civil"],
    budgetRange: "under-50000",
    updatedAt: new Date(),
  },
  {
    id: "sample-7",
    name: "Dell G15",
    brand: "Dell",
    slug: "dell-g15",
    price: 72990,
    specs: {
      ram: "16GB",
      storage: "512GB SSD",
      processor: "Intel Core i5-13450HX",
      gpu: "NVIDIA RTX 3050",
      display: '15.6" FHD 120Hz',
      battery: "Up to 6 hours",
      weight: "2.51 kg",
    },
    image: img("dell-g15"),
    affiliateUrl: "https://www.amazon.in",
    rating: 4.2,
    tags: ["Gaming", "CAD", "Service Network"],
    isRecommended: false,
    branches: ["mechanical"],
    budgetRange: "70000-100000",
    updatedAt: new Date(),
  },
  {
    id: "sample-8",
    name: "ASUS VivoBook Pro 15",
    brand: "ASUS",
    slug: "asus-vivobook-pro-15",
    price: 74990,
    specs: {
      ram: "16GB",
      storage: "512GB SSD",
      processor: "AMD Ryzen 7 5800H",
      gpu: "NVIDIA RTX 3050",
      display: '15.6" OLED FHD',
      battery: "Up to 7 hours",
      weight: "1.8 kg",
    },
    image: img("asus-vivobook-pro-15"),
    affiliateUrl: "https://www.amazon.in",
    rating: 4.4,
    tags: ["OLED Display", "CAD", "Civil"],
    isRecommended: false,
    branches: ["civil", "architecture"],
    budgetRange: "70000-100000",
    updatedAt: new Date(),
  },
  {
    id: "sample-9",
    name: "HP Pavilion 15",
    brand: "HP",
    slug: "hp-pavilion-15",
    price: 54990,
    specs: {
      ram: "16GB",
      storage: "512GB SSD",
      processor: "Intel Core i5-1335U",
      gpu: "Integrated Iris Xe",
      display: '15.6" FHD',
      battery: "Up to 8 hours",
      weight: "1.75 kg",
    },
    image: img("hp-pavilion-15"),
    affiliateUrl: "https://www.amazon.in",
    rating: 4.0,
    tags: ["All-Rounder", "HP Service"],
    isRecommended: false,
    branches: ["civil", "electronics"],
    budgetRange: "50000-70000",
    updatedAt: new Date(),
  },
  {
    id: "sample-10",
    name: "ASUS Zenbook 14",
    brand: "ASUS",
    slug: "asus-zenbook-14",
    price: 69990,
    specs: {
      ram: "16GB",
      storage: "512GB SSD",
      processor: "Intel Core i5-1340P",
      gpu: "Integrated Iris Xe",
      display: '14" OLED 2.8K',
      battery: "Up to 10 hours",
      weight: "1.39 kg",
    },
    image: img("asus-zenbook-14"),
    affiliateUrl: "https://www.amazon.in",
    rating: 4.5,
    tags: ["Ultrabook", "Lightweight", "Battery"],
    isRecommended: false,
    branches: ["electrical"],
    budgetRange: "70000-100000",
    updatedAt: new Date(),
  },
  {
    id: "sample-11",
    name: "Lenovo ThinkPad E14",
    brand: "Lenovo",
    slug: "lenovo-thinkpad-e14",
    price: 62990,
    specs: {
      ram: "16GB",
      storage: "512GB SSD",
      processor: "AMD Ryzen 5 7530U",
      gpu: "Integrated Radeon",
      display: '14" FHD IPS',
      battery: "Up to 9 hours",
      weight: "1.59 kg",
    },
    image: img("lenovo-thinkpad-e14"),
    affiliateUrl: "https://www.amazon.in",
    rating: 4.3,
    tags: ["Business", "Keyboard", "Durable"],
    isRecommended: false,
    branches: ["electronics"],
    budgetRange: "50000-70000",
    updatedAt: new Date(),
  },
  {
    id: "sample-12",
    name: "ASUS Vivobook 15",
    brand: "ASUS",
    slug: "asus-vivobook-15",
    price: 49990,
    specs: {
      ram: "16GB",
      storage: "512GB SSD",
      processor: "Intel Core i5-1335U",
      gpu: "Integrated Iris Xe",
      display: '15.6" FHD',
      battery: "Up to 7 hours",
      weight: "1.7 kg",
    },
    image: img("asus-vivobook-15"),
    affiliateUrl: "https://www.amazon.in",
    rating: 4.1,
    tags: ["Budget", "Electronics"],
    isRecommended: false,
    branches: ["electronics"],
    budgetRange: "50000-70000",
    updatedAt: new Date(),
  },
  {
    id: "sample-13",
    name: "ASUS TUF A15",
    brand: "ASUS",
    slug: "asus-tuf-a15",
    price: 84990,
    specs: {
      ram: "16GB",
      storage: "512GB SSD",
      processor: "AMD Ryzen 7 7735HS",
      gpu: "NVIDIA RTX 4050",
      display: '15.6" FHD 144Hz',
      battery: "Up to 6 hours",
      weight: "2.2 kg",
    },
    image: img("asus-tuf-a15"),
    affiliateUrl: "https://www.amazon.in",
    rating: 4.4,
    tags: ["AI/ML", "Gaming", "GPU"],
    isRecommended: true,
    branches: ["ai"],
    budgetRange: "70000-100000",
    updatedAt: new Date(),
  },
];

export function findLaptopByName(name: string): Laptop | undefined {
  const normalized = name.toLowerCase().trim();
  return SAMPLE_LAPTOPS.find(
    (l) =>
      l.name.toLowerCase() === normalized ||
      normalized.includes(l.name.toLowerCase()) ||
      l.name.toLowerCase().includes(normalized),
  );
}

export const SAMPLE_DEALS: Deal[] = [
  {
    id: "deal-1",
    laptopId: "sample-1",
    laptopName: "Lenovo IdeaPad Slim 5",
    originalPrice: 64990,
    dealPrice: 58990,
    discount: 9,
    platform: "Amazon.in",
    affiliateUrl: "https://www.amazon.in",
    validUntil: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
    isActive: true,
  },
  {
    id: "deal-2",
    laptopId: "sample-2",
    laptopName: "MacBook Air M2",
    originalPrice: 114900,
    dealPrice: 99900,
    discount: 13,
    platform: "Amazon.in",
    affiliateUrl: "https://www.amazon.in",
    validUntil: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000),
    isActive: true,
  },
  {
    id: "deal-3",
    laptopId: "sample-5",
    laptopName: "Lenovo LOQ 15",
    originalPrice: 82990,
    dealPrice: 74990,
    discount: 10,
    platform: "Flipkart",
    affiliateUrl: "https://www.flipkart.com",
    validUntil: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000),
    isActive: true,
  },
];
